<a href="https://colab.research.google.com/github/riddhi-jain/Way-to-Machine-Learning/blob/main/K_Nearest_Neighbours.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
import numpy as np
import sklearn 

In [4]:
from sklearn.datasets import load_iris
data = load_iris()
data.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [5]:
df = pd.DataFrame(data['data'])
df.head()

0    1    2    3
0  5.1  3.5  1.4  0.2
1  4.9  3.0  1.4  0.2
2  4.7  3.2  1.3  0.2
3  4.6  3.1  1.5  0.2
4  5.0  3.6  1.4  0.2

In [6]:
data['target_names']


array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [7]:
x = df
y = data['target']

In [8]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.25, random_state = 0)

In [9]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors = 3)

In [10]:
knn.fit(x_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='uniform')

In [11]:
x_new = np.array([[5,2.9, 1, 0.2]])
pred = knn.predict(x_new)
pred

array([0])

In [12]:
data['target_names'][pred]

array(['setosa'], dtype='<U10')

In [13]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
y_pred = knn.predict(x_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
print(accuracy_score(y_test, y_pred))


[[13  0  0]
 [ 0 15  1]
 [ 0  0  9]]
0.9736842105263158
