<a href="https://colab.research.google.com/github/riddhi-jain/Way-to-Machine-Learning/blob/main/Naive_Bayes_Classifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import sklearn

# Gaussian Naive Bayes

In [4]:
from sklearn.datasets import load_wine
data = load_wine()

In [10]:
df = pd.DataFrame(data['data'], columns= data.feature_names)
df.head()

alcohol  malic_acid   ash  ...   hue  od280/od315_of_diluted_wines  proline
0    14.23        1.71  2.43  ...  1.04                          3.92   1065.0
1    13.20        1.78  2.14  ...  1.05                          3.40   1050.0
2    13.16        2.36  2.67  ...  1.03                          3.17   1185.0
3    14.37        1.95  2.50  ...  0.86                          3.45   1480.0
4    13.24        2.59  2.87  ...  1.04                          2.93    735.0

[5 rows x 13 columns]

In [11]:
data.target_names

array(['class_0', 'class_1', 'class_2'], dtype='<U7')

In [13]:
df.shape

(178, 13)

In [17]:
x = pd.DataFrame(data['data'])
y = data['target']

In [21]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, random_state = 2)

In [22]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()

gnb.fit(x_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [26]:
y_pred = gnb.predict(x_test)

In [30]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
print("Accuracy Score:" , (gnb.score(x_test, y_test))*100, "%")

[[19  1  0]
 [ 0 20  0]
 [ 0  1 13]]
Accuracy Score: 96.29629629629629 %


# Multinomial Naive Bayes

In [48]:
# Sample Example 1
from sklearn.feature_extraction.text import CountVectorizer
corpus = ['This is the first document.',
          'This document is the second document.',
          'And this is the third one.',
          'Is this the first document?']
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(corpus)
vectorizer.get_feature_names()

['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third', 'this']

In [49]:
X.toarray()

array([[0, 1, 1, 1, 0, 0, 1, 0, 1],
       [0, 2, 0, 1, 0, 1, 1, 0, 1],
       [1, 0, 0, 1, 1, 0, 1, 1, 1],
       [0, 1, 1, 1, 0, 0, 1, 0, 1]])

In [31]:
# Sample Example 2
from sklearn.datasets import fetch_20newsgroups
data2 = fetch_20newsgroups()

In [54]:
data2.keys()

dict_keys(['data', 'filenames', 'target_names', 'target', 'DESCR'])

In [44]:
print(len(data2.target_names))
data2.target_names

20


['alt.atheism',
 'comp.graphics',
 'comp.os.ms-windows.misc',
 'comp.sys.ibm.pc.hardware',
 'comp.sys.mac.hardware',
 'comp.windows.x',
 'misc.forsale',
 'rec.autos',
 'rec.motorcycles',
 'rec.sport.baseball',
 'rec.sport.hockey',
 'sci.crypt',
 'sci.electronics',
 'sci.med',
 'sci.space',
 'soc.religion.christian',
 'talk.politics.guns',
 'talk.politics.mideast',
 'talk.politics.misc',
 'talk.religion.misc']

In [36]:
df2 = pd.DataFrame(data2['data'])
df2.head()

0
0  From: lerxst@wam.umd.edu (where's my thing)\nS...
1  From: guykuo@carson.u.washington.edu (Guy Kuo)...
2  From: twillis@ec.ecn.purdue.edu (Thomas E Will...
3  From: jgreen@amber (Joe Green)\nSubject: Re: W...
4  From: jcm@head-cfa.harvard.edu (Jonathan McDow...

In [67]:
y = data2.target

array([7, 4, 4, ..., 3, 1, 8])

In [45]:
# picking a subset of all target_names into which dataset has to be classified
categories = ['comp.windows.x',
              'misc.forsale',
              'rec.autos','alt.atheism',]

In [50]:
count_vector = CountVectorizer()
data2_train = fetch_20newsgroups(subset='train', categories = categories)
data2_test = fetch_20newsgroups(subset='test', categories= categories)

In [55]:
x_train = count_vector.fit_transform(data2_train.data)

In [56]:
print(x_train.toarray())
x_train.shape

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


(2252, 33854)

In [60]:
# TF-IDF is basically considering frequency of words in a document corpus
# TF stands for term frequency

from sklearn.feature_extraction.text import TfidfTransformer
tfidf_transformer = TfidfTransformer()

x_train_tfidf = tfidf_transformer.fit_transform(x_train)
x_train_tfidf.shape

(2252, 33854)

TF-IDF considers frequency of words in a document as well as , frequency in document corpus. Where as Countvectoriser considers word frequency in single document

In [63]:
from sklearn.naive_bayes import MultinomialNB
mnb = MultinomialNB()
mymodel = mnb.fit(x_train_tfidf, data2_train.target)
mymodel

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [65]:
x_test_df = count_vector.transform(data2_test.data)
x_test_tfidf = tfidf_transformer.transform(x_test_df)

pred = mymodel.predict(x_test_tfidf)
pred

array([3, 2, 1, ..., 0, 0, 0])

In [70]:
mnb.score(x_test_tfidf, pred)

1.0